# Generated by Django 6.0 on 2025-12-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials_reviews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, max_length=5, null=True)),
                ('Title_of_your_review', models.CharField(max_length=100)),
                ('Your_review', models.TextField(max_length=200, null=True)),
                ('Your_name', models.CharField(max_length=50)),
                ('Your_email', models.CharField(max_length=120)),
                ('expr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
