# Generated by Django 6.0 on 2025-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
