# Generated by Django 5.2.5 on 2025-12-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_clinicinfo_disease_doctor_livesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='clinic_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
