# Generated by Django 6.0 on 2025-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='doctor-hero.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contact_gallary',
            name='image',
            field=models.ImageField(default='doctor-hero.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='slug',
            field=models.SlugField(default='Disease', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor-hero.jpg', upload_to='doctors/'),
        ),
    ]
