# Generated by Django 5.2.5 on 2025-12-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_clinicinfo_clinic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='about_heading',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='about_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
