# Generated by Django 6.0 on 2025-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_blog_contact_us_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Dr. Ketul Soni', max_length=100),
        ),
    ]
