# Generated by Django 5.2.4 on 2025-12-15 05:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_blog_contact_gallary_faq_gallery_homeopathyabout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeopathy_end_about_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=200)),
                ('about_text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homeopathy_start_about_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=200)),
                ('about_text', models.TextField()),
            ],
        ),
    ]
