# Generated by Django 6.0 on 2026-01-03 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_alter_blog_image_alter_contact_gallary_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Invalid phone number')])),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cencelled', 'Cencelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'time_slot')},
            },
        ),
    ]
