# Generated by Django 6.0 on 2025-12-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_blog_image_alter_blog_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contact_gallary',
        ),
    ]
