# Generated by Django 6.0 on 2026-01-03 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
