# Generated by Django 5.2.5 on 2025-12-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_clinicinfo_about_heading_clinicinfo_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about_points',
            field=models.TextField(default=1, help_text='Enter each point on a new line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
