# Generated by Django 6.0 on 2025-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_rename_contact_us_contact_gallary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='link',
            new_name='youtube_id',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
