# Generated by Django 5.2.5 on 2025-12-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_doctor_about_points_doctor_about_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeopathyAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='homeopathy/')),
                ('points', models.TextField(help_text='Har line ek bullet point hogi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
