# Generated by Django 5.2.5 on 2025-12-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_homeopathyabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeopathyabout',
            name='image',
        ),
    ]
