# Generated by Django 6.0 on 2026-01-03 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_appointment_anonymized_at_appointment_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOOK_ATTEMPT', 'Book Attempt'), ('BOOK_SUCCESS', 'Book Success'), ('BOOK_FAIL', 'Book Fail'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('RATE_LIMIT_BLOCK', 'Rate Limit Block'), ('CAPTCHA_FAIL', 'Captcha Fail')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
