# Generated by Django 6.0 on 2026-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_ratelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
