# Generated by Django 6.0 on 2026-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_alter_appointment_anonymized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
