# Generated by Django 6.0 on 2026-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0012_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
