# Generated by Django 6.0 on 2026-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0014_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
