# Generated by Django 6.0 on 2026-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0015_device_phone_alter_device_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
