# Generated by Django 6.0 on 2026-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0016_alter_notification_recipient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.CharField(max_length=20),
        ),
    ]
