# Generated by Django 6.0 on 2026-01-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0017_alter_notification_recipient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user_id',
        ),
    ]
