# Generated by Django 6.0 on 2026-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0018_remove_device_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
