# Generated by Django 6.0 on 2026-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0019_notification_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user_type', 'phone', 'fcm_token'), name='unique_device_per_user'),
        ),
    ]
