# Generated by Django 6.0 on 2026-01-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0020_device_unique_device_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_off_days', models.JSONField(default=list)),
                ('special_closed_dates', models.JSONField(default=list)),
                ('special_open_dates', models.JSONField(default=list)),
            ],
        ),
    ]
