# Generated by Django 6.0 on 2026-01-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0021_clinicschedule'),
        ('clinic_app', '0022_doctorleave'),
    ]

    operations = [
    ]
