# Generated by Django 6.0 on 2026-01-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0023_merge_0021_clinicschedule_0022_doctorleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='special_closed_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='special_open_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='weekly_off_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
