# Generated by Django 6.0 on 2026-01-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0024_device_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
    ]
