# Generated by Django 6.0.1 on 2026-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0026_alter_disease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
