# Generated by Django 6.0.1 on 2026-01-28 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0028_device_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_device_per_user',
        ),
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'doctor')), fields=('user_type', 'user', 'fcm_token'), name='unique_doctor_device'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('user_type', 'patient')), fields=('user_type', 'phone', 'fcm_token'), name='unique_patient_device'),
        ),
    ]
